[project]
name = "ragflow-cn"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pyyaml",
]

[pip]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"